### ISSUE TITLE
Android 12 Webview and Keyboard

### ISSUE THREAD

**Issue by Sisco21** [p-stannis/flutter_aad_oauth#13]
With the Flutter version 2.10.1 and android 12 devices (Virtual or physic) keyboard don't show up.

Are you aware with this behavior?

Best Regards

**Comment by gadgetboyme** [comment]
This is occurring for me too.
Has there been any investigation or temporary mitigation that we can use to get around this?

**Comment by gadgetboyme** [comment]
The issue appears to be around webview_flutter.
https://stackoverflow.com/questions/70212256/soft-keyboard-stopped-working-in-flutters-webview-on-android-12
Can the webview plugin be updated to 3.0.1?

**Comment by joaovvrodrigues** [comment]
Fixed on #11
